[package]
name = 'NftLaunchpad'
version = '1.0.0'
authors = []

[addresses]
nft_launchpad = "0x4477072c2c9867029b336fd96e27c8f33fcf56088dc3245fce4905e4646e2286"
# @nft_launchpad + seed
collection_creator = "0xec7230d4acbfd48d01b920d5ab5e2644c4be6d1af8abea8dd080de414cbb8ff4"
aptos_token_objects = "0x4"

[dev-addresses]

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-token-objects'

[dev-dependencies]
